"""rename address

Revision ID: 62341b68c384
Revises: 89e98b09178a
Create Date: 2024-07-01 23:43:53.120904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62341b68c384'
down_revision = '89e98b09178a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###